FROM \
	evrinoma/php72:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.2 cont" \
	image="php-7.2" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-01-23"

COPY	cont.conf /etc/httpd/conf.d/vhost.conf
