#!/bin/bash
NAME=squid_devel
RUN=$(ps aux |grep -c "$NAME")
let "RUN = RUN - 3"
if [ "$RUN" -gt "1" ] ; then
	echo "The programm is all ready run :)" >> /var/log/squid/squid_shutdown.log
	exit 0;
fi

TRACE="squid"
ser="LOST"
DEBUG=1
while (true) 
do
	isSquidRunning=`ps aux | grep "squid -f" | grep -v grep`
	found="$(echo $isSquidRunning | awk -F " " '{print($11)}')"
	if [ "$TRACE" == "$found" ] ; then
		ser="FOUND"
	fi
	if [ "$ser" == "LOST" ] ; then
		if [ $DEBUG -eq 1 ] ; then 
			echo "$TRACE disable"; 
		fi
		date >> /var/log/squid/squid_shutdown.log
		date +%s >> /var/log/squid/squid_shutdown.log
		echo /etc/init.d/squid stop
		echo /etc/init.d/squid start
		service squid stop
		service squid start
	else
		echo "$TRACE enable"
	fi
sleep 10
ser="LOST"
done


