FROM \
	evrinoma/php53:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 5.3 webuseorg" \
	image="php-5.3" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-07-29"

COPY	webuseorg.conf /etc/httpd/conf.d/vhost.conf
