#!/bin/bash

###PRIMAVERA_INSERT

DIR="/opt/WWW/container.ite-ng.ru/projects"

if [ ! -d "$LOG_ROOT/primavera" ]; then
	mkdir -p $LOG_ROOT/primavera
	chown oracle:oracle -R $LOG_ROOT/primavera
fi
if [ ! -d "$DIR/primavera" ]; then
        mkdir -p $DIR/primavera
        cp -fr $DOMAIN_HOME $DIR
fi
rm -fr $DOMAIN_HOME
ln -s $DIR/primavera $DOMAIN_HOME
chown oracle:oracle -R $DIR/primavera


