#!/bin/bash
docker build -t evrinoma/db.maria ../../../docker/db/maria/10.3.27/.

docker build -t evrinoma/bind ../../../docker/bind/.

docker build -t evrinoma/dovecot ../../../docker/mail/dovecot/.
docker build -t evrinoma/dovecot.email ../../../docker/mail/dovecot/servers/email/.

docker build -t evrinoma/php74 ../../../docker/php74/.
docker build --build-arg VERSION=1.3.16 -t evrinoma/php74.roundcubemail ../../../docker/php74/sites/roundcubemail/.

docker build -t evrinoma/mattermost ../../../docker/mattermost/.
