#!/bin/bash
docker build -t evrinoma/db.maria ../../../docker/db/maria/.

docker build -t evrinoma/bind ../../../docker/bind/.

docker build -t evrinoma/dovecot ../../../docker/mail/dovecot/.
docker build -t evrinoma/dovecot.email ../../../docker/mail/dovecot/servers/email/.

docker build -t evrinoma/php72 ../../../docker/php72/.
docker build --build-arg VERSION=1.3.10 -t evrinoma/php72.roundcubemail ../../../docker/php72/sites/roundcubemail/.
