version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        hostname: "maria.db"
        ports:
            - "172.16.45.4:3306:3306/tcp"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/docker/src/db/maria/:/var/lib/mysql"
            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    bind_slave:
        container_name: "bind.slave"
        image: "evrinoma/bind.slave"
        hostname: "bind.slave"
        extra_hosts:
            - "git.ite-ng.ru:172.20.1.169"
        ports:
            - "172.16.45.4:53:53/tcp"
            - "172.16.45.4:53:53/udp"
            - "172.16.45.4:8953:8953"
            - "172.16.45.4:12000:22"
        build:
            context: docker/bind/servers/mail/.
            dockerfile: Dockerfile
            args:
                - MODE=slave
                - INSTALL_DIR=/opt/bind
                - GIT_IP=172.20.1.169
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.5.2

    php72_roundcubemail:
        container_name: "php72.roundcubemail"
        image: "evrinoma/php72.roundcubemail"
        hostname: "email.ite-ng.ru"
        ports:
            - "172.16.45.4:80:80/tcp"
            - "172.16.45.4:443:443/tcp"
        build:
            context: docker/php72/sites/roundcubemail/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.11

    mail_dovecot_email:
        container_name: "dovecot.email"
        image: "evrinoma/dovecot.email"
        hostname: "email.ite-ng.ru"
        dns: 172.18.5.2
        ports:
            - "172.16.45.4:25:25/tcp"
            - "172.16.45.4:110:110/tcp"
            - "172.16.45.4:143:143/tcp"
            - "172.16.45.4:465:465/tcp"
            - "172.16.45.4:993:993/tcp"
            - "172.16.45.4:995:995/tcp"
            - "172.16.45.4:8010:80/tcp"
        build:
            context: docker/mail/dovecot/servers/email/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.4.2

networks:
    virt:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "docker_dovecot"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
