version: '2'
services:
    primavera_18:
        container_name: "primavera.18.8.deploy"
        image: "evrinoma/primavera.18.8.deploy"
        hostname: "primavera.ite-ng.ru"
        privileged: true
#rmi server unsupport port forwarding
        network_mode: 'host'
#        ports:
#            - "172.20.1.78:80:7001"
#            - "172.20.1.78:443:7002"
#            - "172.20.1.78:9001:9001"
#            - "172.20.1.78:9099:9099"
#            - "172.20.1.78:5901:5901"
        extra_hosts:
            - "iteng26:172.20.1.26"
        build:
            context: docker/primavera/servers/18.8/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:rw"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#        networks:
#            virt:
#                ipv4_address: 172.18.22.18

    php72_sqladmin:
        container_name: "php72.sqladmin"
        image: "evrinoma/php72.sqladmin"
        build:
            context: docker/php72/sites/sqladmin/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.10

networks:
    virt:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
            com.docker.network.bridge.enable_ip_masquerade: "true"
           com.docker.network.bridge.name: "docker_primavera"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
