#!/bin/bash
####build network
#docker network create lamp

####build php 5
#docker build -t evrinoma/php53 docker/php53/.
#docker build --no-cache -t evrinoma/php71 docker/php71/.
#docker run --rm -t -p 22:22 -v /opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/ --net lamp --name php53 -d evrinoma/php53
#docker push evrinoma/php71

####build php 7
#docker build -t evrinoma/php71 docker/php71/.
#docker build --no-cache -t evrinoma/php71 docker/php71/.
#docker run --rm -t -p 80:80 -v /opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/ --net lamp --name webldap5 -d evrinoma/php71
#docker push evrinoma/php71

####build mariadb
#docker build -t evrinoma/containerdb docker/containerdb/.
#docker build --no-cache -t evrinoma/containerdb docker/containerdb/.
#docker run -p 3306:3306 -v /opt/DISK/Develop/Docker/db/:/var/lib/mysql --net=lamp --name=containerdb -d evrinoma/containerdb
#docker push evrinoma/containerdb

####help
#docker ps -a
#docker rm $(docker ps -a -q -f status=exited)
#docker exec -it 19a93ae69843 bash -1
#docker network inspect lamp
#docker container stop 6
#docker rm $(docker ps -a -q -f status=exited)
#docker images
#docker rmi d30969b16a73
#docker push evrinoma/php71


#docker-compose build
#docker-compose up -d
#docker-compose down