#!/bin/bash
docker build -t evrinoma/db.maria.web ../../../../docker/db/maria/web/.

docker build -t evrinoma/php72 ../../../../docker/php72/.
docker build -t evrinoma/php72.web ../../../../docker/php72/sites/bundle/web/.


