FROM \
		evrinoma/db.maria:latest

MAINTAINER \
		evrinoma@gmail.com

LABEL \
		name="evrinoma Web Maria SQL Image" \
		image="maria.db.web" \
		vendor="evrinoma@gmail.com" \
		license="MIT" \
		build-date="2019-05-21"

COPY	my.cnf /etc/
