version: '2'
services:
    containerdb:
        container_name: "containerdb"
        image: "evrinoma/containerdb"
        build:
            context: docker/containerdb/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/db/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/lamp/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.1.2

    samba:
        container_name: "samba.kis"
        image: "evrinoma/samba.kis"
#        cpu_shares: 100
#        mem_limit: 262144000
        hostname: "SMB_KIS"
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        build:
            context: docker/samba/servers/kis/.
            dockerfile: Dockerfile
        volumes:
#            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.7

    php53_kis_nekeng_ru:
        container_name: "php53.kis.nekeng"
        image: "evrinoma/php53.kis.nekeng.ru"
        build:
            context: docker/php53/sites/kis.nekeng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.5
            
    php53_kis_new_nekeng_ru:
        container_name: "php53.kisnew.nekeng"
        image: "evrinoma/php53.kisnew.nekeng.ru"
        build:
            context: docker/php53/sites/kisnew.nekeng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.6
            
    php53_kis_ite-ng_ru:
        container_name: "php53.kis"
        image: "evrinoma/php53.kis.ite-ng.ru"
        build:
            context: docker/php53/sites/kis.ite-ng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.3
            
    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew"
        image: "evrinoma/php53.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew.ite-ng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

    php72_webldap5:
        container_name: "php72.webldap5"
        image: "evrinoma/php72.webldap5"
        build:
            context: docker/php72/sites/webldap5/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.5
            
    php72_cont:
        container_name: "php72.cont"
        image: "evrinoma/php72.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php72_portal:
        container_name: "php72.portal"
        image: "evrinoma/php72.portal.ite-ng.ru"
        build:
            context: docker/php72/sites/portal/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.7

    php72_sqladmin:
        container_name: "php72.sqladmin"
        image: "evrinoma/php72.sqladmin"
        build:
            context: docker/php72/sites/sqladmin/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/lamp/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.10


networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1



