#!/bin/bash
docker-compose -f ../docker-compose.test.yml down
docker-compose -f ../docker-compose.test.yml build
docker-compose -f ../docker-compose.test.yml up -d 

docker rm $(docker ps -a -q -f status=exited)
for variable in `docker images | grep '<none>' | awk '{ print $3}'`
do
docker rmi "$variable"
done