FROM \
	evrinoma/php72:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.2 cont" \
	image="php-7.2.cont" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2018-04-18"

COPY	cont.conf /etc/httpd/conf.d/vhost.conf
