FROM \
	evrinoma/php71:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.1 empty" \
	image="php-7.1" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2017-02-20"

COPY	empty.conf /etc/httpd/conf.d/vhost.conf
