FROM \
	evrinoma/openmeetings:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma openmeetings Image" \
	image="openmeetings" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2020-09-29"

