#!/bin/bash
docker build -t evrinoma/postgre.1c ../../../../docker/db/postgre/1c/.
docker build -t evrinoma/1c ../../../../docker/1c/.
docker build -t evrinoma/1c.83.17.1851 ../../../../docker/1c/servers/83.17.1851/.
