FROM \
	evrinoma/php72:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.2 tools" \
	image="php-7.2" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2017-02-20"

COPY	tools.conf /etc/httpd/conf.d/vhost.conf
