#!/bin/sh

# WARNING: This file is created by the Configuration Wizard.
# Any changes to this script may be lost when adding extensions to this configuration.

###PRIMAVERA_INSERT

${DOMAIN_HOME}/bin/startWebLogic.sh -Dprimavera.bootstrap.home=$PRIMAVERA -Dweblogic.Stdout=$LOG_PRIMAVERA $*
#-Dweblogic.management.username=$PRIMAVERA_USERNAME -Dweblogic.management.password=$PRIMAVERA_PASSWORD
