#!/bin/sh

# WARNING: This file is created by the Configuration Wizard.
# Any changes to this script may be lost when adding extensions to this configuration.

###PRIMAVERA_INSERT

${DOMAIN_HOME}/bin/stopWebLogic.sh $PRIMAVERA_USERNAME $PRIMAVERA_PASSWORD $*

