#!/bin/bash
DIR="/opt/WWW/container.ite-ng.ru/projects"
LOGS="/opt/WWW/container.ite-ng.ru/logs"

if [ ! -d "$LOGS/primavera" ]; then
    mkdir -p $LOGS/primavera
    chown oracle:oracle -R $LOGS/primavera
fi
if [ ! -d "$DIR/primavera" ]; then
    mkdir -p $DIR
    tar -xvf /opt/Oracle/DOMAIN/primavera.12.2.1.4.tar.gz -C $DIR
    chown oracle:oracle -R $DIR
fi
