version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db/maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/services/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/services/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_roundcubemail:
        container_name: "php72.roundcubemail"
        image: "evrinoma/php72.roundcubemail"
        build:
            context: docker/php72/sites/roundcubemail/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/services/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.11

#    mail_dovecot:
#        container_name: "dovecot"
#        image: "evrinoma/dovecot"
#        build:
#            context: docker/mail/dovecot/.
#            dockerfile: Dockerfile
#        volumes:
#            - "/opt/DISK/Develop/Docker/services/src/:/opt/WWW/container.ite-ng.ru/"
#        networks:
#            virt:
#                ipv4_address: 172.18.4.1

    mail_dovecot_email:
        container_name: "dovecot.email"
        image: "evrinoma/dovecot.email"
        hostname: "email.ite-ng.ru"
#        privileged: true
        build:
            context: docker/mail/dovecot/servers/email/.
            dockerfile: Dockerfile
        volumes:
#            - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
            - "/opt/DISK/Develop/Docker/services/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.4.2

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
