FROM \
	evrinoma/php71:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.1 cont" \
	image="php71.cont" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2018-04-18"

COPY	cont.conf /etc/httpd/conf.d/vhost.conf
