#!/bin/bash

declare -A struct
struct=( [KIS_BANK]=exchangeBankClient [1C_adm]=exchange1C )

if [ "root" != "${PAM_USER}" ]; then
    if [ ! -d "/home/${PAM_USER}" ]; then
    	mkdir -p /home/${PAM_USER}
    fi
    chown root.root /home/${PAM_USER}
    chmod 755 /home/${PAM_USER}

    base=/home/external
    if [ ! -d "$base" ]; then
        	mkdir -p $base
    fi

    for group in ${!struct[*]}
    do
        if [ ! -d "$base/${struct[$group]}" ]; then
                mkdir -p $base/${struct[$group]}
        fi

        chmod -R 770 $base/${struct[$group]}
        chown -R root.$group $base/${struct[$group]}
    done
fi
