#!/bin/bash

###PRIMAVERA_INSERT

DIR="/opt/WWW/container.ite-ng.ru/projects"

if [ ! -d "$LOG_ROOT/primavera" ]; then
	mkdir -p $LOG_ROOT/primavera
	chown oracle:oracle -R $LOG_ROOT/primavera
fi
if [ ! -d "$DIR/primavera" ]; then
	mkdir -p $DIR
	tar -xvf $WEBLOGIC_DOMAIN -C $DIR
	chown oracle:oracle -R $DIR/primavera
fi
