#!/bin/bash

###PRIMAVERA_INSERT

pass=$1
if [ ! -z "$pass" ]; then
		DIR="/opt/WWW/container.ite-ng.ru/projects/primavera"
		if [ ! -d "$LOG_ROOT" ]; then
			mkdir -p $LOG_ROOT
		fi
		if [ ! -d "$DIR" ]; then
			mkdir -p $DIR
            tar -xvf $WEBLOGIC_DOMAIN -C $DIR

			chown oracle:oracle -R $DIR
			chown oracle:oracle -R $LOG_ROOT
		fi
fi
