version: '2'
services:
    containerdb:
        container_name: "containerdb"
        image: "evrinoma/containerdb"
#        cpu_shares: 100
#        mem_limit: 262144000
        build:
            context: docker/containerdb/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/services/src/db/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/services/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.1.2

    mssqldb:
        container_name: "mssqldb"
        image: "microsoft/mssql-server-linux:2017-latest"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "rjk,fcf2008"
            ACCEPT_EULA: "Y"
        volumes:
            - "/opt/DISK/Develop/Docker/services/src/mssql.db/:/var/opt/mssql"
        networks:
            virt:
                ipv4_address: 172.18.1.4

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1


