version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
#            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
#            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
            - "/opt/docker/src/db/maria/:/var/lib/mysql"
            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_web:
        container_name: "php72.web"
        image: "evrinoma/php72.web"
        build:
            context: docker/php72/sites/bundle/web/.
            dockerfile: Dockerfile
        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.24.1

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

