version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        ports:
            - "172.20.1.160:3306:3306/tcp"
        volumes:
            - "/opt/docker/src/db/maria/:/var/lib/mysql"
            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    bind_master:
        container_name: "bind.master"
        image: "evrinoma/bind.master"
        hostname: "bind.master"
        build:
            context: docker/bind/servers/mail/.
            dockerfile: Dockerfile
        ports:
            - "172.20.1.5:53:53/tcp"
            - "172.20.1.5:53:53/udp"
            - "172.20.1.5:8953:8953"
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.5.1

    sftp:
        container_name: "sftp"
        image: "evrinoma/sftp"
        dns: 172.20.1.6
        build:
            context: docker/sftp/.
            dockerfile: Dockerfile
        ports:
            - "172.20.1.160:22:22/tcp"
        volumes:
            - "/opt/DISK_ISCSI/data/sftp/:/home/"
        networks:
            virt:
                ipv4_address: 172.18.20.1

    php72_owncloud:
        container_name: "php72.owncloud"
        image: "evrinoma/php72.owncloud"
        build:
            context: docker/php72/sites/owncloud/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        ports:
            - "172.20.1.160:80:80/tcp"
            - "172.20.1.160:443:443/tcp"
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.14

    php72_cont:
        container_name: "php72.cont"
        image: "evrinoma/php72.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        ports:
            - "172.20.1.165:80:80/tcp"
            - "172.20.1.165:443:443/tcp"
            - "172.20.1.165:22:22/tcp"
        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

networks:
    virt:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "docker_sftp"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

