#!/bin/bash
docker build -t evrinoma/db.maria ../../../../docker/db/maria/5.5.65/.

docker build -t evrinoma/php54 ../../../../docker/php54/.
docker build -t evrinoma/php54.web ../../../../docker/php54/sites/bundle/web/.


