#!/bin/bash
pass=$1
serverSql=172.18.2.1
base=tools
user=contrspam
basepass=contrspam
if [ ! -z "$pass" ]; then
  mariaInstall=`yum list installed | grep "mariadb\."`
  if [ -z "$mariaInstall" ]; then
      yum install mysql -y
  fi

  chmod +x /usr/local/bin/init.sql
  init.sql $pass $serverSql $base $user $basepass
  chmod -x /usr/local/bin/init.sql

  if [ -z "$mariaInstall" ]; then
      yum remove mysql -y
  fi
fi
