FROM \
		evrinoma/primavera.15.1:latest

MAINTAINER \
		evrinoma@gmail.com

LABEL \
	name="evrinoma Primaver 15.1 deploy" \
	image="primavera.15.1.deploy" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-12-24"




