version: '2'
services:
    java_gitlab:
        container_name: "java.gitlab.deploy"
        image: "evrinoma/java.gitlab.deploy"
        privileged: true
        ports:
             - "172.20.1.78:80:80"
#            - "172.20.1.11:8750:8750"
#            - "172.20.1.11:8751:8751"
        build:
            context: docker/java/gitlab/server/.
            dockerfile: Dockerfile
        volumes:
#            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.11

networks:
    virt:
        driver: bridge
#        driver_opts:
#            com.docker.network.enable_ipv6: "false"
#            com.docker.network.bridge.name: "docker_sftp"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

