version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/5.5.65/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_clean:
        container_name: "php72.clean"
        image: "evrinoma/php72.clean"
        build:
            context: docker/php72/sites/clean/.
            dockerfile: Dockerfile
            args:
                - VHOST=clean
                - database_host=172.18.2.1
                - database_name=clean
                - database_port=3306
                - database_user=clean
                - database_password=clean
#                - RUN=init.install 1234
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.26

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
