version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_cont:
        container_name: "php72.cont.public"
        image: "evrinoma/php72.public.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=public
                - database_host=172.18.2.1
                - database_name=cont
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew.public"
        image: "evrinoma/php53.public.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=public
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
#        ports:
#            - "172.20.1.78:81:80/tcp"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

