version: '3'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/10.3.27/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    redis:
        container_name: "redis"
        image: "evrinoma/redis"
        build:
            context: docker/redis/.
            dockerfile: Dockerfile
        ports:
            - 6379:6379
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.14

    ubuntu_gnome_wine:
        container_name: "ubuntu.wine.deploy"
        image: "evrinoma/ubuntu.wine.deploy"
        privileged: true
        build:
            context: docker/wine/ubuntu/.
            dockerfile: Dockerfile
        hostname: "ubuntu.wine"
        extra_hosts:
            - "php53.kis.ite-ng:172.18.53.3"
        ports:
#            - 172.20.1.78:5902:5901
            - 5901:5901
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.25.2

    php74_clean:
        container_name: "php74.clean"
        image: "evrinoma/php74"
        environment:
            - ENGINE=httpd
            - DEPLOY=yes
            - SYMFONY=yes
            - MODE=dev
            - NODEJS=10
            - web_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/clean/public
            - web_server=php74.clean
            - web_alias=clean
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.26

    php80_clean:
        container_name: "php80.clean"
        image: "evrinoma/php80"
        environment:
            - ENGINE=nginx
            - DEPLOY=yes
            - SYMFONY=yes
            - MODE=dev
            - NODEJS=10
            - web_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/clean.php80/public
            - web_server=php80.clean
            - web_alias=clean
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.26

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

