version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/10.3.27/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    redis:
        container_name: "redis"
        image: "evrinoma/redis"
        build:
            context: docker/redis/.
            dockerfile: Dockerfile
        ports:
            - 6379:6379
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.14

    php72_cont:
        container_name: "php72.cont.prod"
        image: "evrinoma/php72.prod.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=prod
                - database_host=172.18.2.1
                - database_name=cont
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php74_tools:
        container_name: "php74.tools"
        image: "evrinoma/php74.tools"
        build:
            context: docker/php74/sites/tools/.
            dockerfile: Dockerfile
#        ports:
#            - 172.20.1.78:80:80
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.4

    php53_kis_ite-ng_ru:
        container_name: "php53.kis.ite-ng"
        image: "evrinoma/php53.kis.ite-ng.ru"
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        build:
            context: docker/php53/sites/kis/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
#        ports:
#            - "172.20.1.78:80:80/tcp"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.3

    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew.ite-ng"
        image: "evrinoma/php53.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
                - exchange=true
                - database_host=172.18.2.1
                - database_name=mh3itgr_ng
                - database_port=3306
                - database_user=mh3itgr_ngdb
                - database_password=147Fort21
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
#        ports:
#            - "172.20.1.78:8080:80/tcp"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

    ubuntu_gnome_wine:
        container_name: "ubuntu.wine.deploy"
        image: "evrinoma/ubuntu.wine.deploy"
        privileged: true
        build:
            context: docker/wine/ubuntu/.
            dockerfile: Dockerfile
        hostname: "ubuntu.wine"
        extra_hosts:
            - "php53.kis.ite-ng:172.18.53.3"
        ports:
#            - 172.20.1.78:5902:5901
            - 5901:5901
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.25.2

    php74_exchange:
        container_name: "php74.exchange"
        image: "evrinoma/php74.exchange"
        build:
            context: docker/php74/sites/exchange/.
            dockerfile: Dockerfile
        environment:
            - MODE=dev
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.29

    php74_supply:
        container_name: "php74.supply"
        image: "evrinoma/php74.supply"
        build:
            context: docker/php74/sites/supply/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.30

#    php74_cont_api:
#        container_name: "php74.cont.api"
#        image: "evrinoma/php74.cont.api"
#        build:
#            context: docker/php74/sites/cont.api/.
#            dockerfile: Dockerfile
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
#        networks:
#            virt:
#                ipv4_address: 172.18.74.31

    php80_cont_api:
        container_name: "php80.cont.api"
        image: "evrinoma/php80"
        environment:
            - DEPLOY=yes
            - SYMFONY=yes
            - MODE=dev
            - httpd_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/cont.api/public
            - httpd_server=php80.cont.api
            - httpd_alias=cont.api
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.31


    php80_tools:
        container_name: "php80.tools"
        image: "evrinoma/php80.tools"
        build:
            context: docker/php80/sites/tools/.
            dockerfile: Dockerfile
#        ports:
#            - 172.20.1.78:80:80
#            - 80:80
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.4

    php80_businesscenter:
        container_name: "php80.bc"
        image: "evrinoma/php80"
        environment:
#            - DEPLOY=yes
#            - MODE=dev
#            - SYMFONY=yes
#            - NODEJS=10
#            - httpd_conf=/opt/WWW/container.ite-ng.ru/projects/httpd/cont.api/vhost.conf
#            - httpd_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/cont.api
            - DEPLOY=yes
            - MODE=dev
            - SYMFONY=yes
            - NODEJS=10
            - httpd_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/businesscenter/public
            - httpd_server=php80.bc
            - httpd_alias=bc
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.32

    php80_clean:
        container_name: "php80.clean"
        image: "evrinoma/php80"
        environment:
            - DEPLOY=yes
            - SYMFONY=yes
            - MODE=dev
            - NODEJS=10
            - httpd_dir=/opt/WWW/container.ite-ng.ru/projects/httpd/clean/public
            - httpd_server=php80.clean
            - httpd_alias=clean
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.26

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
