version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

#    php80_exchange:
#        container_name: "php80.exchange"
#        image: "evrinoma/php80.exchange"
#        build:
#            context: docker/php80/.
#            dockerfile: Dockerfile
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
#        networks:
#            virt:
#                ipv4_address: 172.18.80.29

    php74_exchange:
        container_name: "php74.exchange"
        image: "evrinoma/php74.exchange"
        build:
            context: docker/php74/sites/exchange/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.29

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

