version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_cont:
        container_name: "php72.cont"
        image: "evrinoma/php72.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php72_tools:
        container_name: "php72.tools"
        image: "evrinoma/php72.tools"
        build:
            context: docker/php72/sites/tools/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.4

    php53_kis_ite-ng_ru:
        container_name: "php53.kis"
        image: "evrinoma/php53.kis.ite-ng.ru"
        build:
            context: docker/php53/sites/kis.ite-ng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.3

    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew"
        image: "evrinoma/php53.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew.ite-ng.ru/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

