version: '2'
services:
    1c_83_16_1148_api:
        container_name: "1c.83.16.1148.api"
        image: "evrinoma/1c.83.16.1148.api"
        hostname: "api.1c.ite-ng.ru"
#        ports:
#            - "172.20.1.11:80:80/tcp"
#            - "172.20.1.11:12000:22/tcp"
        build:
            context: docker/1c/servers/83.16.1148/api/.
            dockerfile: Dockerfile
        extra_hosts:
            - "iteng26:172.20.1.26"
            - "1cdebug:172.20.1.94"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.83.160

networks:
    virt:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "docker_sftp"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
