version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_adbook:
        container_name: "php72.adbook"
        image: "evrinoma/php72.adbook"
        ports:
            - "80:80/tcp"
        build:
            context: docker/php72/sites/adbook/.
            dockerfile: Dockerfile
        volumes:
#            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.5

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
