version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/10.3.27/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    redis:
        container_name: "redis"
        image: "evrinoma/redis"
        build:
            context: docker/redis/.
            dockerfile: Dockerfile
        ports:
            - 6379:6379
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.14

    php72_cont:
        container_name: "php72.cont.prod"
        image: "evrinoma/php72.prod.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=prod
                - database_host=172.18.2.1
                - database_name=cont
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php72_cont_master:
        container_name: "php72.cont.master"
        image: "evrinoma/php72.master.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=master
                - database_host=172.18.2.1
                - database_name=cont_master
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.25

    php74_tools:
        container_name: "php74.tools"
        image: "evrinoma/php74.tools"
        build:
            context: docker/php74/sites/tools/.
            dockerfile: Dockerfile
        ports:
            - 172.20.1.78:80:80
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.4

    php53_kis_ite-ng_ru:
        container_name: "php53.kis.ite-ng"
        image: "evrinoma/php53.kis.ite-ng.ru"
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        build:
            context: docker/php53/sites/kis/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
#        ports:
#            - "172.20.1.78:80:80/tcp"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.3

    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew.ite-ng"
        image: "evrinoma/php53.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
                - exchange=true
                - database_host=172.18.2.1
                - database_name=mh3itgr_ng
                - database_port=3306
                - database_user=mh3itgr_ngdb
                - database_password=147Fort21
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
#        ports:
#            - "172.20.1.78:8080:80/tcp"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

    php53_kis_new_nekeng_ru:
        container_name: "php53.kisnew.nekeng"
        image: "evrinoma/php53.kisnew.nekeng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=nekeng
                - exchange=true
                - database_host=172.18.2.1
                - database_name=mh3itgr_nek_ng
                - database_port=3306
                - database_user=mh3itgr_ngdb
                - database_password=147Fort21
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.6

    ubuntu_gnome_wine:
        container_name: "ubuntu.wine.deploy"
        image: "evrinoma/ubuntu.wine.deploy"
        privileged: true
        build:
            context: docker/wine/ubuntu/.
            dockerfile: Dockerfile
        hostname: "ubuntu.wine"
        extra_hosts:
            - "php53.kis.ite-ng:172.18.53.3"
        ports:
#            - 172.20.1.78:5902:5901
            - 5901:5901
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.25.2

    php74_exchange:
        container_name: "php74.exchange"
        image: "evrinoma/php74.exchange"
        build:
            context: docker/php74/sites/exchange/.
            dockerfile: Dockerfile
        environment:
            - NODE_MODE=dev
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.29

    php74_supply:
        container_name: "php74.supply"
        image: "evrinoma/php74.supply"
        build:
            context: docker/php74/sites/supply/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.30

    php74_cont_api:
        container_name: "php74.cont.api"
        image: "evrinoma/php74.cont.api"
        build:
            context: docker/php74/sites/cont.api/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.31

    1c_83_17_1851_api:
        container_name: "1c.83.17.1851.api"
        image: "evrinoma/1c.83.17.1851.api"
        hostname: "api.1c.ite-ng.ru"
#        ports:
#            - "172.20.1.78:80:80/tcp"
        build:
            context: docker/1c/servers/83.17.1851/api/.
            dockerfile: Dockerfile
        extra_hosts:
            - "iteng26:172.20.1.26"
            - "1cdebug:172.20.1.94"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.83.171

    php80_tools:
        container_name: "php80.tools"
        image: "evrinoma/php80.tools"
        build:
            context: docker/php80/sites/tools/.
            dockerfile: Dockerfile
#        ports:
#            - 172.20.1.78:80:80
#            - 80:80
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.80.4

    php80_businesscenter:
        container_name: "php80.businesscenter"
        image: "evrinoma/php80.businesscenter"
        build:
            context: docker/php80/sites/businesscenter/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.80.32

    mattermost:
        container_name: "mattermost.5.31.0"
        image: "evrinoma/mattermost.5.31.0"
        build:
            context: docker/mattermost/servers/.
            dockerfile: Dockerfile
            args:
                - VERSION=5.31.0
                - VHOST=mattermost
                - database_host=172.18.2.1
                - database_name=mattermost
                - database_port=3306
                - database_user=mattermost
                - database_password=mattermost
#        ports:
#            - 172.20.1.78:443:443
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.200.31

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
