version: '2'
services:
    maria_db:
        container_name: "maria.db.public"
        image: "evrinoma/db.maria.public"
        build:
            context: docker/db/maria/public/.
            dockerfile: Dockerfile
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_tools:
        container_name: "php72.tools.public"
        image: "evrinoma/php72.tools.public"
        build:
            context: docker/php72/sites/tools/public/.
            dockerfile: Dockerfile
        networks:
            virt:
                ipv4_address: 172.18.72.4

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

