version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/5.5.65/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    sftp:
        container_name: "sftp.cloud"
        image: "evrinoma/sftp.cloud"
        dns: 172.20.1.6
        build:
            context: docker/sftp/servers/cloud/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.20.1
    sftp_kis:
        container_name: "sftp.kis"
        image: "evrinoma/sftp.kis"
        dns: 172.20.1.6
        build:
            context: docker/sftp/servers/kis/.
            dockerfile: Dockerfile
        volumes:
            #            - "/opt/DISK_ISCSI/data/sftp/:/home/"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        #            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.20.2

    php72_owncloud:
        container_name: "php72.owncloud"
        image: "evrinoma/php72.owncloud"
        build:
            context: docker/php72/sites/cloud/servers/owncloud/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.14

    php72_kiscloud:
        container_name: "php72.kiscloud"
        image: "evrinoma/php72.kiscloud"
        build:
            context: docker/php72/sites/cloud/servers/kiscloud/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.21

networks:
    virt:
        driver: bridge
#        driver_opts:
#            com.docker.network.enable_ipv6: "false"
#            com.docker.network.bridge.name: "docker_sftp"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

