version: '2'
services:
    bind_master:
        container_name: "bind.master"
        image: "evrinoma/bind.master"
        hostname: "bind.master"
        build:
            context: docker/bind/servers/mail/.
            dockerfile: Dockerfile
            args:
                - MODE=slave
                - INSTALL_DIR=/opt/bind
#        ports:
#            - "172.20.1.5:53:53/tcp"
#            - "172.20.1.5:53:53/udp"
#            - "172.20.1.5:8953:8953"
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.5.1

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

