version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php74_roundcubemail:
        container_name: "php74.roundcubemail"
        image: "evrinoma/php74.roundcubemail"
        hostname: "email.ite-ng.ru"
#        ports:
#            - "172.16.45.4:80:80/tcp"
#            - "172.16.45.4:443:443/tcp"
        build:
            context: docker/php74/sites/roundcubemail/.
            dockerfile: Dockerfile
            args:
                - VERSION=1.3.10
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.74.11

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

