version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    php72_cont:
        container_name: "php72.cont.prod"
        image: "evrinoma/php72.prod.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=prod
                - database_host=172.18.2.1
                - database_name=cont
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.6

    php72_cont_master:
        container_name: "php72.cont.master"
        image: "evrinoma/php72.master.cont.ite-ng.ru"
        build:
            context: docker/php72/sites/cont/.
            dockerfile: Dockerfile
            args:
                - VHOST=master
                - database_host=172.18.2.1
                - database_name=cont_master
                - database_port=3306
                - database_user=cont
                - database_password=cont
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.25

    php72_tools:
        container_name: "php72.tools"
        image: "evrinoma/php72.tools"
        build:
            context: docker/php72/sites/tools/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.72.4

    php53_kis_ite-ng_ru:
        container_name: "php53.kis.ite-ng"
        image: "evrinoma/php53.kis.ite-ng.ru"
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        build:
            context: docker/php53/sites/kis/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
#        ports:
#            - "172.20.1.78:80:80/tcp"
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.3

    php53_kis_new_ite-ng_ru:
        container_name: "php53.kisnew.ite-ng"
        image: "evrinoma/php53.kisnew.ite-ng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=ite-ng
                - exchange=true
                - database_host=172.18.2.1
                - database_name=mh3itgr_ng
                - database_port=3306
                - database_user=mh3itgr_ngdb
                - database_password=147Fort21
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
#        ports:
#            - "172.20.1.78:8080:80/tcp"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.4

    php53_kis_new_nekeng_ru:
        container_name: "php53.kisnew.nekeng"
        image: "evrinoma/php53.kisnew.nekeng.ru"
        build:
            context: docker/php53/sites/kisnew/.
            dockerfile: Dockerfile
            args:
                - VHOST=nekeng
                - exchange=true
                - database_host=172.18.2.1
                - database_name=mh3itgr_nek_ng
                - database_port=3306
                - database_user=mh3itgr_ngdb
                - database_password=147Fort21
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/Docker/src/data_sftp_kis/external/:/opt/WWW/external/"
        networks:
            virt:
                ipv4_address: 172.18.53.6

    ubuntu_gnome_wine:
        container_name: "ubuntu.wine.deploy"
        build:
            context: docker/wine/ubuntu/.
            dockerfile: Dockerfile
        hostname: "ubuntu.wine"
        extra_hosts:
            - "php53.kis.ite-ng:172.18.53.3"
        ports:
            - 5901:5902
            - 9001:9001
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/DISK/Develop/Docker/src/conf/wine/:/root/.wine/"
        networks:
            virt:
                ipv4_address: 172.18.25.2

    php74_exchange:
        container_name: "php74.exchange"
        image: "evrinoma/php74.exchange"
        build:
            context: docker/php74/sites/exchange/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.29

    php74_supply:
        container_name: "php74.supply"
        image: "evrinoma/php74.supply"
        build:
            context: docker/php74/sites/supply/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK/Develop/PhpStorm/PhpstormProjects/:/opt/WWW/container.ite-ng.ru/PhpstormProjects/"
        networks:
            virt:
                ipv4_address: 172.18.74.30

#    open_mcu:
#        container_name: "evrinoma.openmcu"
#        image: "johannrichard/openmcu"
#        ports:
#            - 5060:5060
#            - 5061:5061
#            - 1420:1420
#            - 1554:1554
#            - 1719:1719
#            - 1720:1720
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#        networks:
#            virt:
#                ipv4_address: 172.18.40.1

#    open_mcu:
#        container_name: "evrinoma.openmcu"
#        image: "johannrichard/openmcu"
#        build:
#            context: docker/openmcu/.
#            dockerfile: Dockerfile
#        ports:
#            - 5000:5999:5000:5999
#            - 1420:1420
#            - 1554:1554
#            - 1719-1720:1719-1720
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#        networks:
#            virt:
#                ipv4_address: 172.18.40.2

#    open_meeting:
#        container_name: "evrinoma.openmeeting"
#        image: "evrinoma/openmeetings:5.0.1"
#        build:
#            context: docker/openmeetings/.
#            dockerfile: Dockerfile
#        environment:
#            - OM_KURENTO_WS_URL=ws://172.18.40.4:8888/kurento
#            - OM_DB_HOST=172.18.2.1
#            - OM_DB_USER=root
#            - OM_DB_PASS=116ip4
#            - OM_DB_NAME=openmeetings
#        ports:
#            - 5443:5443
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/omdata/:/opt/WWW/container.ite-ng.ru/omdata/"
#        networks:
#            virt:
#                ipv4_address: 172.18.40.3

#    kurento:
#        container_name: "evrinoma.kms"
#        image: "kurento/kurento-media-server"
#        environment:
#            - KMS_MIN_PORT=5000
#            - KMS_MAX_PORT=5050
#        ports:
#            - 8888:8888/tcp
#            - 5000-5050:5000-5050/udp
#        volumes:
#            - "/opt/DISK/Develop/Docker/src/omdata/kms:/opt/WWW/container.ite-ng.ru/omdata/kms"
#        networks:
#            virt:
#                ipv4_address: 172.18.40.4

    open_meeting:
        container_name: "evrinoma.openmeeting"
        image: "evrinoma/openmeetings:latest"
        environment:
            - OM_KURENTO_WS_URL=ws://172.18.40.4:8888/kurento
            - OM_DB_HOST=172.18.2.1
            - OM_DB_USER=openmeetings
            - OM_DB_PASS=openmeetings
            - OM_DB_NAME=openmeetings
        ports:
            - 5443:5443
        volumes:
            - "/opt/DISK/Develop/Docker/src/omdata/:/opt/WWW/container.ite-ng.ru/omdata/"
        networks:
            virt:
                ipv4_address: 172.18.40.3

    kurento:
        container_name: "evrinoma.kms"
        image: "evrinoma/kurento:latest"
        environment:
            - KMS_MIN_PORT=5000
            - KMS_MAX_PORT=5050
        ports:
            - 8888:8888/tcp
            - 5000-5050:5000-5050/udp
        volumes:
            - "/opt/DISK/Develop/Docker/src/omdata/kms:/opt/WWW/container.ite-ng.ru/omdata/kms"
        networks:
            virt:
                ipv4_address: 172.18.40.4

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
