version: '2'
services:
    vnc_primavera:
        container_name: "primavera.15.1.1.deploy"
        image: "evrinoma/primavera.15.1.1.deploy"
        build:
            context: docker/primavera/servers/15.1.1/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:rw"
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.22.15

    mssql_db:
        container_name: "mssqldb.db"
        image: "microsoft/mssql-server-linux:2017-latest"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Q1w2e3r4t5y6"
            ACCEPT_EULA: "Y"
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/mssql.db/:/var/opt/mssql"
        networks:
            virt:
                ipv4_address: 172.18.2.3

    php72_sqladmin:
        container_name: "php72.sqladmin"
        image: "evrinoma/php72.sqladmin"
        build:
            context: docker/php72/sites/sqladmin/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.10

networks:
    virt:
        driver: bridge
#        driver_opts:
#            com.docker.network.enable_ipv6: "false"
#            com.docker.network.bridge.name: "docker_sftp"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

