version: '2'
services:
    wowza_4_7_7:
        container_name: "wowza.4.7.7"
        image: "evrinoma/wowza.versions.4.7.7"
        build:
            context: docker/wowza/versions/4.7.7/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.14.77

    sftp:
        container_name: "sftp"
        image: "evrinoma/sftp"
        build:
            context: docker/sftp/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.15.1

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1

