FROM \
		evrinoma/redmine:latest

MAINTAINER \
		evrinoma@gmail.com

LABEL \
		name="evrinoma BackUp Deploy Image" \
		image="redmina.deploy" \
		vendor="evrinoma@gmail.com" \
		license="MIT" \
		build-date="2019-12-13"
