FROM \
		evrinoma/redmine:latest

MAINTAINER \
		evrinoma@gmail.com

LABEL \
		name="evrinoma Redmine Deploy Image" \
		image="redmine.deploy" \
		vendor="evrinoma@gmail.com" \
		license="MIT" \
		build-date="2019-12-20"
