#!/bin/bash

createHttpdConfig() {
DST_FILE=$1
if [ ! -z "${DST_FILE}" ] ; then
echo '####################################################
### container.ite-ng.ru/###HTTPD_ALIAS
####################################################
<VirtualHost *:80>
	Alias /###HTTPD_ALIAS ###HTTPD_DIR
	ServerName ###HTTPD_SERVER
	ServerAlias ###HTTPD_SERVER_ALIAS
	ServerAdmin ###HTTPD_ADMIN_EMAIL
	DocumentRoot "###HTTPD_DIR"
	ErrorLog /var/log/httpd/error-###HTTPD_ALIAS.log
	CustomLog /var/log/httpd/access-###HTTPD_ALIAS.log combined
	<Directory "###HTTPD_DIR/">
		AllowOverride All
		Require all granted
		<IfModule mod_rewrite.c>
			Options -MultiViews
			RewriteEngine On
			RewriteCond %{REQUEST_FILENAME} !-f
			RewriteRule ^(.*)$ index.php [QSA,L]
		</IfModule>
	</Directory>
</VirtualHost>
' > $DST_FILE
fi
}

declare -A ARGS

ARGS=( [SHOW]= [PASSWD]= [YUM]= [DEPLOY]= [SYMFONY]= [MODE]=dev [VHOST]= [database_host]= [database_name]= [database_port]= [database_user]= [database_password]= [httpd_dir]= [httpd_conf]= [httpd_server]= [httpd_server_alias]= [httpd_alias]= [httpd_admin_email]=nikolns@ite-ng.ru [NODEJS]= )
STATUS=''
FILE_NAME=sys.credentials

for KEY in "${!ARGS[@]}";
do
    if [ ! -z $(printenv $KEY) ] ; then
	    ARGS[$KEY]=$(printenv $KEY)
    fi
done

if [ -z "${ARGS[httpd_server_alias]}" ]; then
    ARGS[httpd_server_alias]=php$(php -v | sed -e "/^PHP/!d" -e "s/.* \([0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/" -e "s/\(.*\)[0-9])*/\1/" -e "s/[^0-9]//g").${ARGS[httpd_alias]}
fi

if [ ! -z "${ARGS[SHOW]}" ]; then
  for KEY in "${!ARGS[@]}";
  do
      echo [$KEY] = ${ARGS[$KEY]};
  done
else
  for KEY in "${!ARGS[@]}";
  do
      unset $KEY
  done
fi

if [ "${ARGS[MODE]}" == "prod" ]; then
  echo ".";
  rm -rf /etc/php.d/xdebug.ini
  rm -rf /root/src
  for value in "$(ls /usr/local/bin/ | grep -ve 'container' | grep 'init.')" ;
  do
     rm -rf /root/src/$value
  done
  echo '' > /root/.bash_history
fi

if [ ! -z "${ARGS[YUM]}" ]; then echo "." && rpm -e --nodeps yum ; fi

if [[ ! -z "${ARGS[PASSWD]}" && -d "/root/install" && -f "/root/install/${FILE_NAME}" ]] ; then
  echo "."
  echo $(cat /root/install/${FILE_NAME} | grep PASSWD | sed -r 's/.*=(.*)$/\1/') | passwd --stdin root > /dev/null
fi

if [[ ! -z "${ARGS[DEPLOY]}" && ! -z "${ARGS[httpd_dir]}" &&  -d "${ARGS[httpd_dir]}" ]] ; then
  if [ ! -z "${ARGS[NODEJS]}" ] ; then
	    STATUS=$(curl -Is https://rpm.nodesource.com/setup_${ARGS[NODEJS]}.x | head -1 | grep "200")
		if [ ! -z "${STATUS}" ] ; then
		    rm -rf /var/cache/yum && \
		    yum remove -y nodejs && \
		    yum clean all && \
		    curl --silent --location https://rpm.nodesource.com/setup_${ARGS[NODEJS]}.x | bash -  && \
		    yum install -y nodejs yarn
		fi
	fi
	if [[  ! -z "${ARGS[httpd_conf]}" &&  -f "${ARGS[httpd_conf]}" ]] ; then
		echo "DEPLOYING...."
		echo "copy ${ARGS[httpd_conf]} to /etc/httpd/conf.d/"
		cp ${ARGS[httpd_conf]} /etc/httpd/conf.d/vhost.conf
		echo "permission apache.apache ${ARGS[httpd_dir]}"
		chown -R apache.apache ${ARGS[httpd_dir]}
		restartHttpd

		exit 0
	fi
	if [[  ! -z "${ARGS[SYMFONY]}" &&  ! -z "${ARGS[httpd_server]}" && ! -z "${ARGS[httpd_alias]}" ]] ; then
		echo "DEPLOYING SYMFONY...."
		createHttpdConfig /etc/httpd/conf.d/vhost.conf
		#sed -i -e "s@###HTTPD_ALIAS@${ARGS[httpd_alias]}@g" /etc/httpd/conf.d/vhost.conf
        #sed -i -e "s@###HTTPD_SERVER_ALIAS@${ARGS[httpd_server_alias]}@g" /etc/httpd/conf.d/vhost.conf
        #sed -i -e "s@###HTTPD_SERVER@${ARGS[httpd_server]}@g" /etc/httpd/conf.d/vhost.conf
        #sed -i -e "s@###HTTPD_DIR@${ARGS[httpd_dir]}@g" /etc/httpd/conf.d/vhost.conf
        #sed -i -e "s/###HTTPD_ADMIN_EMAIL/${ARGS[httpd_admin_email]}/g" /etc/httpd/conf.d/vhost.conf
		sed -i -e "s@###HTTPD_ALIAS@${ARGS[httpd_alias]}@g" -i -e "s@###HTTPD_SERVER_ALIAS@${ARGS[httpd_server_alias]}@g" -i -e "s@###HTTPD_SERVER@${ARGS[httpd_server]}@g" -i -e "s@###HTTPD_DIR@${ARGS[httpd_dir]}@g" -i -e "s/###HTTPD_ADMIN_EMAIL/${ARGS[httpd_admin_email]}/g" /etc/httpd/conf.d/vhost.conf
		echo "permission apache.apache ${ARGS[httpd_dir]}"
		chown -R apache.apache ${ARGS[httpd_dir]}/..
		restartHttpd
		exit 0
	fi
fi

rm -rf /root/install