#!/bin/bash
docker build -t evrinoma/db.maria ../../../docker/db/maria/.

docker build -t evrinoma/php53 ../../../docker/php53/.

docker build -t evrinoma/node ../../../docker/node/.

docker build -t evrinoma/samba ../../../docker/samba/.

