version: '2'
services:
    dante:
        container_name: "dante"
        image: "evrinoma/dante"
        build:
            context: docker/dante/.
            dockerfile: Dockerfile
        networks:
            docker1:
                ipv4_address: 172.18.1.3
networks:
    docker1:
        external: true