FROM \
	evrinoma/php53:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 5.3 kisnew.ite-ng.ru" \
	image="php-5.3" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2018-09-13"

COPY	kisnew.ite-ng.ru.conf /etc/httpd/conf.d/vhost.conf
