FROM \
	kurento/kurento-media-server:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma kurento Image" \
	image="kurento" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2020-09-29"

