#!/bin/bash

dockerComposeFile=$1
if [ ! -z "$dockerComposeFile" ]; then
	docker-compose -f $dockerComposeFile down
	docker-compose -f $dockerComposeFile build 
	#--no-cache
	docker-compose -f $dockerComposeFile up -d 
	./clean.builds
	./clean.containers
fi
