#!/bin/bash

docerComposeFile=$1
if [ ! -z "$docerComposeFile" ]; then
	docker-compose -f $docerComposeFile down
	docker-compose -f $docerComposeFile build 
	#--no-cache
	docker-compose -f $docerComposeFile up -d 
	./clean.builds
	./clean.containers
fi
