#!/bin/bash

SERVERS=([8070]=172.18.72.4 [8090]=172.18.1.6 [8100]=172.18.53.12 [8110]=172.18.53.3 )
bridge=$(brctl show | grep -e "br" | grep -e "veth" | awk {'print $1'})

echo $bridge

for index in ${!SERVERS[*]}
do
    iptables -t nat -A DOCKER ! -i $bridge -p tcp -m tcp --dport $index -j DNAT --to-destination ${SERVERS[$index]}:80
    iptables -t filter -A DOCKER -d ${SERVERS[$index]}/32 ! -i $bridge -o $bridge -p tcp -m tcp --dport 80 -j ACCEPT
done
