#!/bin/bash
docker build -t evrinoma/vnc ../docker/vnc/.
docker build -t evrinoma/primavera.15.1 ../docker/primavera/15.1/.

#docker build -t evrinoma/ruby265 ../docker/ruby265/.
#docker build -t evrinoma/redmine ../docker/ruby265/servers/redmine/.

#docker build -t evrinoma/java ../docker/java/.
#docker build -t evrinoma/java.gitlab ../docker/java/gitlab/version/12.5.5/.
#docker build -t evrinoma/java.jenkins ../docker/java/jenkins/.
#docker build -t evrinoma/backup ../docker/backup/.

#docker build -t evrinoma/samba ../docker/samba/.
#docker build -t evrinoma/squid ../docker/squid/.
#docker build -t evrinoma/postgre.1c ../docker/db/postgre/1c/.
#docker build -t evrinoma/1c ../docker/1c/.
#docker build -t evrinoma/1c.83.13.1644 ../docker/1c/servers/83.13.1644/.
#docker build -t evrinoma/1c.83.15.1700 ../docker/1c/servers/83.15.1700/.

#docker build -t evrinoma/dovecot ../docker/mail/dovecot/.
#docker build -t evrinoma/bind ../docker/bind/.
#docker build -t evrinoma/exim ../docker/mail/exim/.
#docker build -t evrinoma/db.maria ../docker/db/maria/.

#docker build -t evrinoma/php53 ../docker/php53/.
#docker build -t evrinoma/php53.new.ite-ng.ru ../docker/php53/sites/kisnew.ite-ng.ru/.
#docker build -t evrinoma/php53.kisnew.ite-ng.ru ../docker/php53/sites/kisnew.ite-ng.ru/.
#docker build -t evrinoma/php53.h.kisnew.ite-ng.ru ../docker/hidden/servers/kisnew.ite-ng.ru/.

#docker build -t evrinoma/php54 ../docker/php54/. 

#docker build -t evrinoma/php72 ../docker/php72/.
#docker build -t evrinoma/php72.cont.ite-ng.ru ../docker/php72/sites/cont/.
#docker build -t evrinoma/php72.cont.ite-ng.ru ../docker/php72/sites/cont/.
#docker build -t evrinoma/php72.h.cont.ite-ng.ru ../docker/hidden/servers/cont/.

#docker build -t evrinoma/wowza ../docker/wowza/.

