#!/bin/bash
#docker build -t evrinoma/ubuntu.vnc ../docker/vnc/ubuntu/.
#docker build -t evrinoma/centos.vnc ../docker/vnc/centos/.
#docker build -t evrinoma/primavera.15.1.1 ../docker/primavera/15.1.1/.
#docker build -t evrinoma/primavera.18.8 ../docker/primavera/18.8/.

#docker build -t evrinoma/ruby265 ../docker/ruby265/.
#docker build -t evrinoma/redmine ../docker/ruby265/servers/redmine/.

#docker build -t evrinoma/java ../docker/java/.
#docker build -t evrinoma/java.gitlab ../docker/java/gitlab/version/12.5.5/.
#docker build -t evrinoma/java.jenkins ../docker/java/jenkins/.
#docker build -t evrinoma/backup ../docker/backup/.

#docker build -t evrinoma/samba ../docker/samba/.
#docker build -t evrinoma/squid ../docker/squid/.
#docker build -t evrinoma/postgre.1c ../docker/db/postgre/1c/.

#docker build -t evrinoma/1c ../docker/1c/.
#docker build -t evrinoma/1c.83.13.1644 ../docker/1c/servers/83.13.1644/.
#docker build -t evrinoma/1c.83.15.1700 ../docker/1c/servers/83.15.1700/.
#docker build -t evrinoma/1c.83.16.1148 ../docker/1c/servers/83.16.1148/.

#docker build -t evrinoma/db.maria ../docker/db/maria/.

#docker build -t evrinoma/bind ../docker/bind/.
#docker build -t evrinoma/exim ../docker/mail/exim/.
#docker build -t evrinoma/dovecot ../docker/mail/dovecot/.

#docker build -t evrinoma/php53 ../docker/php53/.
#docker build -t evrinoma/php53.new.ite-ng.ru ../docker/php53/sites/kisnew.ite-ng.ru/.
#docker build -t evrinoma/php53.kisnew.ite-ng.ru ../docker/php53/sites/kisnew.ite-ng.ru/.
#docker build -t evrinoma/php53.h.kisnew.ite-ng.ru ../docker/hidden/servers/kisnew.ite-ng.ru/.

#docker build -t evrinoma/php54 ../docker/php54/. 

#docker build -t evrinoma/php72 ../docker/php72/.
#docker build -t evrinoma/php72.cont.ite-ng.ru ../docker/php72/sites/cont/.
#docker build -t evrinoma/php72.cont.ite-ng.ru ../docker/php72/sites/cont/.
#docker build -t evrinoma/php72.h.cont.ite-ng.ru ../docker/hidden/servers/cont/.
#docker build -t evrinoma/php72.owncloud ../docker/php72/sites/cloud/servers/owncloud/.
#docker build -t evrinoma/php72.kiscloud ../docker/php72/sites/cloud/servers/kiscloud/.

#docker build -t evrinoma/php74 ../docker/php74/.
#docker build -t evrinoma/php80 ../docker/php80/.

#docker build -t evrinoma/php74.exchange ../docker/php74/sites/exchange/.
#docker build -t evrinoma/php74.supply ../docker/php74/sites/supply/.

#docker build -t evrinoma/wowza ../docker/wowza/.

#docker build -t evrinoma/sftp  ../docker/sftp/. --no-cache
#docker build -t evrinoma/sftp.cloud  ../docker/sftp/servers/cloud/. --no-cache
#docker build -t evrinoma/sftp.kis  ../docker/sftp/servers/kis/. --no-cache

#docker build -t evrinoma/node ../docker/node/.

#docker build -t evrinoma/php72.asterisk17 ../docker/php72/sites/freepbx/asterisk17/.
#docker build -t evrinoma/php72.asterisk13 ../docker/php72/sites/freepbx/asterisk13/.

#docker build -t evrinoma/kurento ../docker/kurento/.
#docker build -t evrinoma/openmeetings ../docker/openmeetings/.
