#!/bin/bash
docker login
docker push evrinoma/db.maria:latest
#docker push evrinoma/php72.cont.ite-ng.ru:latest
#docker push evrinoma/php53.kisnew.ite-ng.ru:latest
#docker push evrinoma/php72:latest
#docker push evrinoma/db.maria.public:latest
#docker push evrinoma/php72.clean.public:latest
#docker push evrinoma/php53.kisnew.nekeng.ru:latest
#docker push evrinoma/php53.kisnew.ite-ng.ru:latest
#docker push evrinoma/php72.cont.ite-ng.ru:latest
#docker push evrinoma/php72.master.cont.ite-ng.ru:latest
#docker push evrinoma/php74.exchange:latest
#docker push evrinoma/php74.supply:latest
#docker push evrinoma/redis:latest
#docker push evrinoma/php74.cont.api:latest
#docker push evrinoma/php80.businesscenter:latest
#docker push evrinoma/php53:latest
#docker push evrinoma/php72:latest
docker push evrinoma/php74:latest
docker push evrinoma/php80:latest
