#!/bin/bash
docker push evrinoma/db.maria:latest
#docker push evrinoma/php72.cont.ite-ng.ru:latest
#docker push evrinoma/php53.kisnew.ite-ng.ru:latest
#docker push evrinoma/php72:latest
#docker push evrinoma/db.maria.public:latest
#docker push evrinoma/php72.tools.public:latest
docker push evrinoma/php53.public.kisnew.ite-ng.ru:latest
docker push evrinoma/php72.public.cont.ite-ng.ru:latest
