FROM \
	evrinoma/php53:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 5.3 webldap" \
	image="php-5.3" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-05-13"

COPY	webldap.conf /etc/httpd/conf.d/vhost.conf
