#!/bin/bash
pass=$1
serverSql=172.18.2.1
base=nekeng
user=nekeng
basepass=nekeng
if [ ! -z "$pass" ]; then
		DIR="/opt/WWW/container.ite-ng.ru/projects/nekeng.ru"
		if [ ! -d "$DIR" ]; then
			mkdir -p $DIR
			tar -zxf /tmp/nekeng.sql.tar.gz -C /tmp
			tar -zxf /tmp/nekeng.tar.gz -C $DIR
			mv $DIR/nekeng.ru/*  $DIR/nekeng.ru/.[^.]* $DIR/
			rm -rf $DIR/nekeng.ru/
			chown apache:apache -R $DIR
			cd $DIR
			init.sql $pass $serverSql $base $user $basepass
		fi
fi
