FROM \
	evrinoma/php71:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.1 webldap5" \
	image="php71.webldap" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2017-02-20"

COPY	webldap5.conf /etc/httpd/conf.d/vhost.conf
