version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db/maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/docker/src/db/maria/:/var/lib/mysql"
            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    bind_master:
        container_name: "bind.slave"
        image: "evrinoma/bind.slave"
        hostname: "bind.slave"
        build:
            context: docker/bind/server/mail/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.5.1

    php72_tools:
        container_name: "php72.tools"
        image: "evrinoma/php72.tools"
        build:
            context: docker/php72/sites/tools/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.4


networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
