version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/db/maria/:/var/lib/mysql"
            - "/opt/DISK/Develop/Docker/src/logs/mariadb/:/var/log/mariadb"
#            - "/opt/docker/src/db/maria/:/var/lib/mysql"
#            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    bind_master:
        container_name: "bind.master"
        image: "evrinoma/bind.master"
        hostname: "bind.master"
        build:
            context: docker/bind/servers/mail/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.5.1

    mail_exim_mail:
        container_name: "exim.mail"
        image: "evrinoma/exim.mail"
        hostname: "mail.ite-ng.ru"
        dns: 172.18.5.1
        build:
            context: docker/mail/exim/servers/mail/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.4.1



    php72_tools:
        container_name: "php72.tools"
        image: "evrinoma/php72.tools"
        build:
            context: docker/php72/sites/tools/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.4

    wowza_4_7_7:
        container_name: "wowza.4.7.7"
        image: "evrinoma/wowza.versions.4.7.7"
        build:
            context: docker/wowza/versions/4.7.7/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.14.77

    sftp:
        container_name: "sftp"
        image: "evrinoma/sftp"
        build:
            context: docker/sftp/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
    #        - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.15.1

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
