FROM \
		evrinoma/primavera.18.8:latest

MAINTAINER \
		evrinoma@gmail.com

LABEL \
	name="evrinoma Primaver 18.8 deploy" \
	image="primavera.18.8.deploy" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2020-03-04"
