#!/bin/bash
docker build -t evrinoma/db.maria ../../../docker/db/maria/.
docker build -t evrinoma/php72 ../../../docker/php72/.
docker build -t evrinoma/1c ../../../docker/1c/.
docker build -t evrinoma/1c.83.15.1700 ../../../docker/1c/servers/83.15.1700/.
docker build -t evrinoma/samba ../../../docker/samba/.
docker build -t evrinoma/squid ../../../docker/squid/.
docker build -t evrinoma/java ../../../docker/java/.
docker build -t evrinoma/java.jenkins ../../../docker/java/java.jenkins/.
docker build -t evrinoma/java.gitlab ../../../docker/java/gitlab/version/12.5.5/.
docker build -t evrinoma/backup ../../../docker/backup/.
