version: '2'
services:
    maria_db:
        container_name: "maria.db"
        image: "evrinoma/db.maria"
        hostname: "maria.db"
        build:
            context: docker/db/maria/.
            dockerfile: Dockerfile
        ports:
            - "172.20.1.161:3306:3306/tcp"
        volumes:
            - "/opt/docker/src/db/maria/:/var/lib/mysql"
            - "/opt/docker/src/logs/mariadb/:/var/log/mariadb"
        networks:
            virt:
                ipv4_address: 172.18.2.1

    squid_77:
        container_name: "squid.77"
        image: "evrinoma/squid.77"
        hostname: "squid77.smb.ite-ng.ru"
        cap_add:
            - SYS_RESOURCE
            - SYS_TIME
        dns:
            - 172.20.1.6
            - 172.20.1.20
        ports:
              #172.20.1.77
            - "172.20.1.77:3128:3128"
        build:
            context: docker/squid/servers/77/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.77

#    java_gitblit:
#        container_name: "java.gitblit"
#        image: "evrinoma/java.gitblit"
#        ports:
#            - "172.20.1.11:8749:8749"
#            - "172.20.1.11:8750:8750"
#            - "172.20.1.11:8751:8751"
#        build:
#            context: docker/java/gitblit/.
#            dockerfile: Dockerfile
#        volumes:
#            - "/etc/localtime:/etc/localtime:ro"
#            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
#        networks:
#            virt:
#                ipv4_address: 172.18.1.10

    java_gitlab:
        container_name: "java.gitlab.deploy"
        image: "evrinoma/java.gitlab.deploy"
        privileged: true
        ports:
             - "172.20.1.169:80:80"
             - "172.20.1.169:22:22"
        build:
            context: docker/java/gitlab/server/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.11

    java_jenkins_deploy:
        container_name: "java.jenkins.deploy"
        image: "evrinoma/java.jenkins.deploy"
        ports:
             - "172.20.1.167:80:8080"
        build:
            context: docker/java/jenkins/server/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.12

    backup_deploy:
        container_name: "backup.deploy"
        image: "evrinoma/backup.deploy"
        ports:
             - "172.20.1.168:22:22"
        build:
            context: docker/backup/servers/.
            dockerfile: Dockerfile
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/DISK_ISCSI/:/opt/WWW/backup/"
##            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.13

    redmine:
        container_name: "redmine.deploy"
        image: "evrinoma/redmine.deploy"
        ports:
            - "172.20.1.170:80:80/tcp"
        build:
            context: docker/ruby265/servers/redmine/4.0.5/.
            dockerfile: Dockerfile
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.1.14

    1c_83_15_1700_api:
        container_name: "1c.83.15.1700.api"
        image: "evrinoma/1c.83.15.1700.api"
        hostname: "api.1c.ite-ng.ru"
        ports:
            - "172.20.1.11:80:80/tcp"
            - "172.20.1.11:12000:22/tcp"
        build:
            context: docker/1c/servers/83.15.1700/api/.
            dockerfile: Dockerfile
        extra_hosts:
            - "iteng26:172.20.1.26"
            - "1cdebug:172.20.1.94"
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.83.150

    php72_adbook:
        container_name: "php72.adbook"
        image: "evrinoma/php72.adbook"
        ports:
            - "172.20.1.161:80:80/tcp"
            - "172.20.1.161:22:22/tcp"
        build:
            context: docker/php72/sites/adbook/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.5

    php72_portal:
        container_name: "php72.portal"
        image: "evrinoma/php72.portal.ite-ng.ru"
        ports:
            - "172.20.1.162:80:80/tcp"
            - "172.20.1.162:22:22/tcp"
        build:
            context: docker/php72/sites/portal/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.7

    php72_sqladmin:
        container_name: "php72.sqladmin"
        image: "evrinoma/php72.sqladmin"
        build:
            context: docker/php72/sites/sqladmin/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
        ports:
            - "172.20.1.166:80:80/tcp"
        volumes:
#            - "/opt/DISK/Develop/Docker/src/:/opt/WWW/container.ite-ng.ru/"
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.10

    php72_pmc_ite-ng_ru:
        container_name: "php72.pmc.ite"
        image: "evrinoma/php72.pmc.ite"
        hostname: "cmp.ite-ng.ru"
        ports:
            - "172.20.1.163:80:80/tcp"
            - "172.20.1.163:22:22/tcp"
        build:
            context: docker/php72/sites/pmc/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
                - VHOST=ite-ng
                - database_host=172.20.1.18
                - database_port=1433
                - database_name=ASU_ITE
                - database_user=PMAdmin
                - database_password=PMAdmin
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.19

    php72_pmc_kzkt45_ru:
        container_name: "php72.pmc.kzkt45"
        image: "evrinoma/php72.pmc.kzkt45"
        hostname: "cmp.kzkt45.ru"
        ports:
            - "172.20.1.164:80:80/tcp"
            - "172.20.1.164:22:22/tcp"
        build:
            context: docker/php72/sites/pmc/.
            dockerfile: Dockerfile
            args:
                - MODE=prod
                - VHOST=kzkt45
                - database_host=172.20.1.18
                - database_port=1434
                - database_name=ASU_ITE_KZKT
                - database_user=PMAdmin
                - database_password=PMAdmin
        volumes:
            - "/opt/docker/src/:/opt/WWW/container.ite-ng.ru/"
        networks:
            virt:
                ipv4_address: 172.18.72.20

networks:
    virt:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "docker_bundle"
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
