#!/bin/bash
pass=$1
serverSql=172.18.2.1
base=kzkt45
user=kzkt45
basepass=kzkt45
if [ ! -z "$pass" ]; then
		DIR="/opt/WWW/container.ite-ng.ru/projects/kzkt45.ru"
		if [ ! -d "$DIR" ]; then
			mkdir -p $DIR
			tar -zxf /root/kzkt45.sql.tar.gz -C /root
			tar -zxf /root/kzkt45.tar.gz -C $DIR
			mv $DIR/kzkt45.ru/*  $DIR/kzkt45.ru/.[^.]* $DIR/
			rm -rf $DIR/kzkt45.ru/
			chown apache:apache -R $DIR
			cd $DIR
			init.sql $pass $serverSql $base $user $basepass
		fi
fi
