#!/bin/bash 
#mkdir -v /home/usr1cv8/.1cv8
#chown usr1cv8.grp1cv8 /home/usr1cv8/.1cv8
#mount --bind /opt/WWW/container.ite-ng.ru/conf/1c/16.1148/.1cv8 /home/usr1cv8/.1cv8
#rm -f /var/run/srv1cv83.pid
#/etc/init.d/srv1cv83 start

mkdir -p /opt/WWW/container.ite-ng.ru/conf/1c/17.1549/.1cv8
mkdir -p /home/usr1cv8/.1cv8
mount --bind /opt/WWW/container.ite-ng.ru/conf/1c/17.1549/.1cv8 /home/usr1cv8/.1cv8
chown usr1cv8.grp1cv8 /home/usr1cv8/.1cv8
rm -f /var/run/srv1cv83.pid
/etc/init.d/srv1cv83 start
