FROM \
	evrinoma/php53:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 5.3 kisnew.nekeng.ru" \
	image="php53.new.nekeng.ru" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2018-08-13"

COPY	kisnew.nekeng.ru.conf /etc/httpd/conf.d/vhost.conf
