FROM \
	evrinoma/php72.tools:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.2 tools" \
	image="php72.tools.public" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-12-05"

ADD install/project.tar.gz /opt/WWW/container.ite-ng.ru/

