FROM \
	evrinoma/php53:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma PHP 7.2 jp.ite-ng.ru" \
	image="php72.jp.ite-ng.ru" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-11-01"

COPY	jp.ite-ng.ru.conf /etc/httpd/conf.d/vhost.conf
