FROM \
	evrinoma/vnc:latest

MAINTAINER \
	evrinoma@gmail.com

LABEL \
	name="evrinoma Primaver 15.1" \
	image="primavera.15.1" \
	vendor="evrinoma@gmail.com" \
	license="MIT" \
	build-date="2019-09-05"

RUN	mkdir -v /opt/Oracle/ && \
	mkdir -v /opt/Oracle/CSIntgSrv && \
	mkdir -v /opt/Oracle/DOMAIN && \
	mkdir -v /opt/Oracle/INVENTORY && \
	mkdir -v /opt/Oracle/JAVA && \
	mkdir -v /opt/Oracle/LOG && \
	mkdir -v /opt/Oracle/P6 && \
	mkdir -v /opt/Oracle/Scheduler && \
	mkdir -v /opt/Oracle/WEBLOGIC && \
	mkdir -v /opt/Oracle/Work

